train:
  seed: 0
  gpu: 0
  model_path: 'dataset/dataset_45_new/69'
  export_path: './outputs'
  train_tag:
  epochs: 100
  internal_epochs: 30
  enable_train: true
  learning_rate: 0.00005
  lambda_l1: 0.1
  ckpt_interval: 1
  ckpt_epoch: -1
  export_video: true
  video_interval: 1
  prompt: "a rubber bear bouncing on a surface"

model:
  network: 'knn'
  normalize_features: true
  hidden_size: 768
  depth: 0 # do not use attention
  num_heads: 8
  mlp_ratio: 2
  num_groups: 4096
  group_size: 16

material:
  # center: [0.5, 0.5, 0.5]
  size: [1.0, 1.0, 1.0]
  rho: 1000.0
  elasticity_physicals:
  - 'CorotatedElasticity'
  - 'StVKElasticity'
  - 'SigmaElasticity'
  - 'VolumeElasticity'
  plasticity_physicals:
  - 'IdentityPlasticity'
  - 'DruckerPragerPlasticity'
  - 'SigmaPlasticity'
  - 'VonMisesPlasticity'
    # For saving GPU memory. May need to balance label when uncommenting. 
  elasticity: 'neural'
  plasticity: 'neural'

render:
  white_bg: false
  mpm_space_vertical_upward_axis: [0, 1, 0]
  mpm_space_viewpoint_center: [0.8, 0.7, 0.7]
  default_camera_index: -1
  show_hint: false
  init_azimuthm: 170
  init_elevation: 0
  init_radius: 1.6
  move_camera: false
  delta_a: -2.4
  delta_e: 0.8
  delta_r: 0.0

preprocessing:
  scale_factor: 0.5
  opacity_threshold: 0.0
  rotation_degree: [0.0]
  rotation_axis: [0]
  sim_area:
  particle_filling:

sim:
  num_grids: 24
  dt: 0.00013
  gravity: [0.0, -9.8, 0.0]
  frames_per_stage: 5
  num_frames: 150
  num_skip_frames: 5
  steps_per_frame: 10
  clip_bound: 0.5
  damping: 1.0
  boundary_conditions:
  - type: 'surface_collider'
    point: [0.0, 0.22, 0.0]
    normal: [0.0, 1.0, 0.0]
    surface: 'sticky'
    friction: 0.0
    start_time: 0.0
    end_time: 1e3
